# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callRMultinom <- function(x) {
    .Call('_IPTM2_callRMultinom', PACKAGE = 'IPTM2', x)
}

multinom_vec <- function(nSample, props) {
    .Call('_IPTM2_multinom_vec', PACKAGE = 'IPTM2', nSample, props)
}

which_int <- function(value, x) {
    .Call('_IPTM2_which_int', PACKAGE = 'IPTM2', value, x)
}

which_num <- function(value, x) {
    .Call('_IPTM2_which_num', PACKAGE = 'IPTM2', value, x)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call('_IPTM2_rdirichlet_cpp', PACKAGE = 'IPTM2', num_samples, alpha_m)
}

rbinom_mat <- function(probmat) {
    .Call('_IPTM2_rbinom_mat', PACKAGE = 'IPTM2', probmat)
}

which_cpp <- function(value, x) {
    .Call('_IPTM2_which_cpp', PACKAGE = 'IPTM2', value, x)
}

pdmat <- function(currentZ, currentC, nIP) {
    .Call('_IPTM2_pdmat', PACKAGE = 'IPTM2', currentZ, currentC, nIP)
}

History <- function(edge, p_d, node, when) {
    .Call('_IPTM2_History', PACKAGE = 'IPTM2', edge, p_d, node, when)
}

Degree <- function(history, node, sender) {
    .Call('_IPTM2_Degree', PACKAGE = 'IPTM2', history, node, sender)
}

Dyadic <- function(history, node, sender) {
    .Call('_IPTM2_Dyadic', PACKAGE = 'IPTM2', history, node, sender)
}

Triadic <- function(history, node, sender) {
    .Call('_IPTM2_Triadic', PACKAGE = 'IPTM2', history, node, sender)
}

Triadic_reduced <- function(triadic) {
    .Call('_IPTM2_Triadic_reduced', PACKAGE = 'IPTM2', triadic)
}

Netstats_cpp <- function(historyIP, node, netstat) {
    .Call('_IPTM2_Netstats_cpp', PACKAGE = 'IPTM2', historyIP, node, netstat)
}

MultiplyXB <- function(X, B) {
    .Call('_IPTM2_MultiplyXB', PACKAGE = 'IPTM2', X, B)
}

MultiplyXBList <- function(X, B) {
    .Call('_IPTM2_MultiplyXBList', PACKAGE = 'IPTM2', X, B)
}

UpdateDenom <- function(alpha, nwordtable) {
    .Call('_IPTM2_UpdateDenom', PACKAGE = 'IPTM2', alpha, nwordtable)
}

UpdateNum <- function(vec, nKwordtable) {
    .Call('_IPTM2_UpdateNum', PACKAGE = 'IPTM2', vec, nKwordtable)
}

tabulateC <- function(x, max) {
    .Call('_IPTM2_tabulateC', PACKAGE = 'IPTM2', x, max)
}

lambda_cpp <- function(p_d, XB) {
    .Call('_IPTM2_lambda_cpp', PACKAGE = 'IPTM2', p_d, XB)
}

TopicInEqZ <- function(K, currentZ_d, alpha, mvec) {
    .Call('_IPTM2_TopicInEqZ', PACKAGE = 'IPTM2', K, currentZ_d, alpha, mvec)
}

WordInEqZ <- function(K, textlistd, tableW, beta, nvec) {
    .Call('_IPTM2_WordInEqZ', PACKAGE = 'IPTM2', K, textlistd, tableW, beta, nvec)
}

EdgeInEqZ_Gibbs <- function(iJi, lambda, delta) {
    .Call('_IPTM2_EdgeInEqZ_Gibbs', PACKAGE = 'IPTM2', iJi, lambda, delta)
}

EdgeInEqZ_Gibbs2 <- function(iJi, lambda, delta) {
    .Call('_IPTM2_EdgeInEqZ_Gibbs2', PACKAGE = 'IPTM2', iJi, lambda, delta)
}

TimeObsInEqZ <- function(LambdaiJi, observedtdiff, observediJi, eta) {
    .Call('_IPTM2_TimeObsInEqZ', PACKAGE = 'IPTM2', LambdaiJi, observedtdiff, observediJi, eta)
}

lambdaiJi <- function(p_d, XB, iJi) {
    .Call('_IPTM2_lambdaiJi', PACKAGE = 'IPTM2', p_d, XB, iJi)
}

DataAug_cpp <- function(iJi_di, lambda_di, XB, p_d, delta, timeinc_d, i, j) {
    .Call('_IPTM2_DataAug_cpp', PACKAGE = 'IPTM2', iJi_di, lambda_di, XB, p_d, delta, timeinc_d, i, j)
}

DataAug_cpp_Gibbs <- function(iJi_di, lambda_di, XB, p_d, delta, eta, timeinc_d, j) {
    .Call('_IPTM2_DataAug_cpp_Gibbs', PACKAGE = 'IPTM2', iJi_di, lambda_di, XB, p_d, delta, eta, timeinc_d, j)
}

expconst <- function(consts) {
    .Call('_IPTM2_expconst', PACKAGE = 'IPTM2', consts)
}

EdgeTime <- function(iJi, lambda, delta, eta, LambdaiJi, observedtdiff, observediJi) {
    .Call('_IPTM2_EdgeTime', PACKAGE = 'IPTM2', iJi, lambda, delta, eta, LambdaiJi, observedtdiff, observediJi)
}

