# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callRMultinom <- function(x) {
    .Call('IPTM2_callRMultinom', PACKAGE = 'IPTM2', x)
}

multinom_vec <- function(nSample, props) {
    .Call('IPTM2_multinom_vec', PACKAGE = 'IPTM2', nSample, props)
}

which_int <- function(value, x) {
    .Call('IPTM2_which_int', PACKAGE = 'IPTM2', value, x)
}

which_num <- function(value, x) {
    .Call('IPTM2_which_num', PACKAGE = 'IPTM2', value, x)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call('IPTM2_rdirichlet_cpp', PACKAGE = 'IPTM2', num_samples, alpha_m)
}

rbinom_mat <- function(probmat) {
    .Call('IPTM2_rbinom_mat', PACKAGE = 'IPTM2', probmat)
}

History <- function(edge, node, when) {
    .Call('IPTM2_History', PACKAGE = 'IPTM2', edge, node, when)
}

Degree <- function(history, node, sender) {
    .Call('IPTM2_Degree', PACKAGE = 'IPTM2', history, node, sender)
}

Dyadic <- function(history, node, sender) {
    .Call('IPTM2_Dyadic', PACKAGE = 'IPTM2', history, node, sender)
}

Triadic <- function(history, node, sender) {
    .Call('IPTM2_Triadic', PACKAGE = 'IPTM2', history, node, sender)
}

Triadic_reduced <- function(triadic) {
    .Call('IPTM2_Triadic_reduced', PACKAGE = 'IPTM2', triadic)
}

MultiplyXBList <- function(X, B) {
    .Call('IPTM2_MultiplyXBList', PACKAGE = 'IPTM2', X, B)
}

MultiplyXBList2 <- function(X, B) {
    .Call('IPTM2_MultiplyXBList2', PACKAGE = 'IPTM2', X, B)
}

UpdateDenom <- function(alpha, nwordtable) {
    .Call('IPTM2_UpdateDenom', PACKAGE = 'IPTM2', alpha, nwordtable)
}

UpdateNum <- function(vec, nKwordtable) {
    .Call('IPTM2_UpdateNum', PACKAGE = 'IPTM2', vec, nKwordtable)
}

tabulateC <- function(x, max) {
    .Call('IPTM2_tabulateC', PACKAGE = 'IPTM2', x, max)
}

lambda_cpp <- function(p_d, XB) {
    .Call('IPTM2_lambda_cpp', PACKAGE = 'IPTM2', p_d, XB)
}

TopicInEqZ <- function(K, currentZ_d, alpha, mvec, doc) {
    .Call('IPTM2_TopicInEqZ', PACKAGE = 'IPTM2', K, currentZ_d, alpha, mvec, doc)
}

WordInEqZ <- function(K, textlistd, tableW, beta, nvec) {
    .Call('IPTM2_WordInEqZ', PACKAGE = 'IPTM2', K, textlistd, tableW, beta, nvec)
}

EdgeInEqZ <- function(iJi, lambda, delta) {
    .Call('IPTM2_EdgeInEqZ', PACKAGE = 'IPTM2', iJi, lambda, delta)
}

EdgeInEqZ_Gibbs <- function(iJi, lambda, delta) {
    .Call('IPTM2_EdgeInEqZ_Gibbs', PACKAGE = 'IPTM2', iJi, lambda, delta)
}

EdgeInEqZ_Gibbs2 <- function(iJi, lambda, delta) {
    .Call('IPTM2_EdgeInEqZ_Gibbs2', PACKAGE = 'IPTM2', iJi, lambda, delta)
}

TimeInEqZ <- function(LambdaiJi, observedtdiff) {
    .Call('IPTM2_TimeInEqZ', PACKAGE = 'IPTM2', LambdaiJi, observedtdiff)
}

ObservedInEqZ <- function(observediJi) {
    .Call('IPTM2_ObservedInEqZ', PACKAGE = 'IPTM2', observediJi)
}

lambdaiJi <- function(p_d, XB, iJi) {
    .Call('IPTM2_lambdaiJi', PACKAGE = 'IPTM2', p_d, XB, iJi)
}

DataAug_cpp <- function(iJi_di, lambda_di, XB, p_d, delta, timeinc_d, i, j) {
    .Call('IPTM2_DataAug_cpp', PACKAGE = 'IPTM2', iJi_di, lambda_di, XB, p_d, delta, timeinc_d, i, j)
}

DataAug_cpp_Gibbs <- function(iJi_di, lambda_di, XB, p_d, delta, timeinc_d, j) {
    .Call('IPTM2_DataAug_cpp_Gibbs', PACKAGE = 'IPTM2', iJi_di, lambda_di, XB, p_d, delta, timeinc_d, j)
}

