# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mahalanobis <- function(x, center, cov) {
    .Call('_IPTMnew_Mahalanobis', PACKAGE = 'IPTMnew', x, center, cov)
}

ei <- function(M) {
    .Call('_IPTMnew_ei', PACKAGE = 'IPTMnew', M)
}

dmvnorm_arma <- function(x, mean, sigma) {
    .Call('_IPTMnew_dmvnorm_arma', PACKAGE = 'IPTMnew', x, mean, sigma)
}

rmvnorm_arma <- function(n, mu, Sigma) {
    .Call('_IPTMnew_rmvnorm_arma', PACKAGE = 'IPTMnew', n, mu, Sigma)
}

priorsum <- function(var, mu, x) {
    .Call('_IPTMnew_priorsum', PACKAGE = 'IPTMnew', var, mu, x)
}

transpose <- function(x) {
    .Call('_IPTMnew_transpose', PACKAGE = 'IPTMnew', x)
}

callRMultinom <- function(x) {
    .Call('_IPTMnew_callRMultinom', PACKAGE = 'IPTMnew', x)
}

multinom_vec <- function(nSample, props) {
    .Call('_IPTMnew_multinom_vec', PACKAGE = 'IPTMnew', nSample, props)
}

which_int <- function(value, x) {
    .Call('_IPTMnew_which_int', PACKAGE = 'IPTMnew', value, x)
}

which_num <- function(value, x) {
    .Call('_IPTMnew_which_num', PACKAGE = 'IPTMnew', value, x)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call('_IPTMnew_rdirichlet_cpp', PACKAGE = 'IPTMnew', num_samples, alpha_m)
}

which_cpp <- function(value, x) {
    .Call('_IPTMnew_which_cpp', PACKAGE = 'IPTMnew', value, x)
}

expconst <- function(consts) {
    .Call('_IPTMnew_expconst', PACKAGE = 'IPTMnew', consts)
}

History <- function(edge, timestamps, cd, node, d, timeunit) {
    .Call('_IPTMnew_History', PACKAGE = 'IPTMnew', edge, timestamps, cd, node, d, timeunit)
}

Degree <- function(history, node, sender) {
    .Call('_IPTMnew_Degree', PACKAGE = 'IPTMnew', history, node, sender)
}

Dyadic <- function(history, node, sender) {
    .Call('_IPTMnew_Dyadic', PACKAGE = 'IPTMnew', history, node, sender)
}

Triadic <- function(history, node, sender) {
    .Call('_IPTMnew_Triadic', PACKAGE = 'IPTMnew', history, node, sender)
}

Netstats_cpp <- function(history, node, netstat) {
    .Call('_IPTMnew_Netstats_cpp', PACKAGE = 'IPTMnew', history, node, netstat)
}

inner <- function(x, y) {
    .Call('_IPTMnew_inner', PACKAGE = 'IPTMnew', x, y)
}

MultiplyXB <- function(X, B) {
    .Call('_IPTMnew_MultiplyXB', PACKAGE = 'IPTMnew', X, B)
}

tabulateC <- function(x, max) {
    .Call('_IPTMnew_tabulateC', PACKAGE = 'IPTMnew', x, max)
}

TopicWord <- function(K, z_d, textlistd, tableW, tableCd, alpha, alpha0, beta, V, w) {
    .Call('_IPTMnew_TopicWord', PACKAGE = 'IPTMnew', K, z_d, textlistd, tableW, tableCd, alpha, alpha0, beta, V, w)
}

TopicWord0 <- function(K, tableW, tableCd, alpha, alpha0, beta, V) {
    .Call('_IPTMnew_TopicWord0', PACKAGE = 'IPTMnew', K, tableW, tableCd, alpha, alpha0, beta, V)
}

Topicpart <- function(K, z_d, tableCd, alpha, alpha0) {
    .Call('_IPTMnew_Topicpart', PACKAGE = 'IPTMnew', K, z_d, tableCd, alpha, alpha0)
}

lmultinom <- function(lprops) {
    .Call('_IPTMnew_lmultinom', PACKAGE = 'IPTMnew', lprops)
}

u_Gibbs <- function(u_di, lambda_di, delta, j) {
    .Call('_IPTMnew_u_Gibbs', PACKAGE = 'IPTMnew', u_di, lambda_di, delta, j)
}

Edgepart <- function(u, lambda, delta) {
    .Call('_IPTMnew_Edgepart', PACKAGE = 'IPTMnew', u, lambda, delta)
}

Edgepartsum <- function(X, B, u, delta) {
    .Call('_IPTMnew_Edgepartsum', PACKAGE = 'IPTMnew', X, B, u, delta)
}

mu_vec <- function(timemat, node, eta) {
    .Call('_IPTMnew_mu_vec', PACKAGE = 'IPTMnew', timemat, node, eta)
}

mu_mat <- function(timemat, node, eta, cd) {
    .Call('_IPTMnew_mu_mat', PACKAGE = 'IPTMnew', timemat, node, eta, cd)
}

Timepart <- function(mu, sigma_tau, a_d, t_d) {
    .Call('_IPTMnew_Timepart', PACKAGE = 'IPTMnew', mu, sigma_tau, a_d, t_d)
}

Timepartsum <- function(mumat, sigma_tau, senders, timestamps) {
    .Call('_IPTMnew_Timepartsum', PACKAGE = 'IPTMnew', mumat, sigma_tau, senders, timestamps)
}

