# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call('_IPTM_dmvnrm_arma', PACKAGE = 'IPTM', x, mean, sigma, logd)
}

priorsum <- function(var, mu, x) {
    .Call('_IPTM_priorsum', PACKAGE = 'IPTM', var, mu, x)
}

transpose <- function(x) {
    .Call('_IPTM_transpose', PACKAGE = 'IPTM', x)
}

callRMultinom <- function(x) {
    .Call('_IPTM_callRMultinom', PACKAGE = 'IPTM', x)
}

multinom_vec <- function(nSample, props) {
    .Call('_IPTM_multinom_vec', PACKAGE = 'IPTM', nSample, props)
}

which_int <- function(value, x) {
    .Call('_IPTM_which_int', PACKAGE = 'IPTM', value, x)
}

which_num <- function(value, x) {
    .Call('_IPTM_which_num', PACKAGE = 'IPTM', value, x)
}

rdirichlet_cpp <- function(num_samples, alpha_m) {
    .Call('_IPTM_rdirichlet_cpp', PACKAGE = 'IPTM', num_samples, alpha_m)
}

which_cpp <- function(value, x) {
    .Call('_IPTM_which_cpp', PACKAGE = 'IPTM', value, x)
}

pdmat <- function(z, l, nIP) {
    .Call('_IPTM_pdmat', PACKAGE = 'IPTM', z, l, nIP)
}

History <- function(edge, p_d, node, when) {
    .Call('_IPTM_History', PACKAGE = 'IPTM', edge, p_d, node, when)
}

Degree <- function(history, node, sender) {
    .Call('_IPTM_Degree', PACKAGE = 'IPTM', history, node, sender)
}

Dyadic <- function(history, node, sender) {
    .Call('_IPTM_Dyadic', PACKAGE = 'IPTM', history, node, sender)
}

Triadic <- function(history, node, sender) {
    .Call('_IPTM_Triadic', PACKAGE = 'IPTM', history, node, sender)
}

Triadic_reduced <- function(triadic) {
    .Call('_IPTM_Triadic_reduced', PACKAGE = 'IPTM', triadic)
}

Netstats_cpp <- function(historyIP, node, netstat) {
    .Call('_IPTM_Netstats_cpp', PACKAGE = 'IPTM', historyIP, node, netstat)
}

inner <- function(x, y) {
    .Call('_IPTM_inner', PACKAGE = 'IPTM', x, y)
}

ximat <- function(timemat, eta, node) {
    .Call('_IPTM_ximat', PACKAGE = 'IPTM', timemat, eta, node)
}

xi_all <- function(timemat, eta, node, edgetrim) {
    .Call('_IPTM_xi_all', PACKAGE = 'IPTM', timemat, eta, node, edgetrim)
}

MultiplyYeta <- function(Y, eta) {
    .Call('_IPTM_MultiplyYeta', PACKAGE = 'IPTM', Y, eta)
}

MultiplyXB <- function(X, B) {
    .Call('_IPTM_MultiplyXB', PACKAGE = 'IPTM', X, B)
}

UpdateDenom <- function(alpha, nwordtable) {
    .Call('_IPTM_UpdateDenom', PACKAGE = 'IPTM', alpha, nwordtable)
}

UpdateNum <- function(vec, nKwordtable) {
    .Call('_IPTM_UpdateNum', PACKAGE = 'IPTM', vec, nKwordtable)
}

tabulateC <- function(x, max) {
    .Call('_IPTM_tabulateC', PACKAGE = 'IPTM', x, max)
}

lambda_cpp <- function(p_d, XB) {
    .Call('_IPTM_lambda_cpp', PACKAGE = 'IPTM', p_d, XB)
}

mu_cpp <- function(p_d, xi) {
    .Call('_IPTM_mu_cpp', PACKAGE = 'IPTM', p_d, xi)
}

mu_vec <- function(p_d, xi) {
    .Call('_IPTM_mu_vec', PACKAGE = 'IPTM', p_d, xi)
}

mu_mat <- function(p_d, xi, edgetrim) {
    .Call('_IPTM_mu_mat', PACKAGE = 'IPTM', p_d, xi, edgetrim)
}

TopicInEqZ <- function(K, z_d, alpha, mvec) {
    .Call('_IPTM_TopicInEqZ', PACKAGE = 'IPTM', K, z_d, alpha, mvec)
}

WordInEqZ <- function(K, textlistd, tableW, beta, V) {
    .Call('_IPTM_WordInEqZ', PACKAGE = 'IPTM', K, textlistd, tableW, beta, V)
}

u_Gibbs <- function(u_di, lambda_di, delta, j) {
    .Call('_IPTM_u_Gibbs', PACKAGE = 'IPTM', u_di, lambda_di, delta, j)
}

expconst <- function(consts) {
    .Call('_IPTM_expconst', PACKAGE = 'IPTM', consts)
}

Edgepart <- function(u, lambda, delta) {
    .Call('_IPTM_Edgepart', PACKAGE = 'IPTM', u, lambda, delta)
}

Timepart <- function(mu, sigma2_tau, a_d, t_d) {
    .Call('_IPTM_Timepart', PACKAGE = 'IPTM', mu, sigma2_tau, a_d, t_d)
}

Timepartsum <- function(mumat, sigma2_tau, senders, timeinc, edgetrim) {
    .Call('_IPTM_Timepartsum', PACKAGE = 'IPTM', mumat, sigma2_tau, senders, timeinc, edgetrim)
}

geometric_mean <- function(data) {
    .Call('_IPTM_geometric_mean', PACKAGE = 'IPTM', data)
}

