# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

UpdateDenom <- function(alpha, nwordtable) {
    .Call('IPTM_UpdateDenom', PACKAGE = 'IPTM', alpha, nwordtable)
}

UpdateNum <- function(vec, nKwordtable) {
    .Call('IPTM_UpdateNum', PACKAGE = 'IPTM', vec, nKwordtable)
}

SortedZ <- function(nIP, currentC, currentZ) {
    .Call('IPTM_SortedZ', PACKAGE = 'IPTM', nIP, currentC, currentZ)
}

SortedC <- function(nIP, currentC, edge) {
    .Call('IPTM_SortedC', PACKAGE = 'IPTM', nIP, currentC, edge)
}

MultiplyXB <- function(X, beta) {
    .Call('IPTM_MultiplyXB', PACKAGE = 'IPTM', X, beta)
}

MultiplyXBList <- function(X, beta) {
    .Call('IPTM_MultiplyXBList', PACKAGE = 'IPTM', X, beta)
}

BetaInEqB <- function(nIP, lambdamat, edgebyC) {
    .Call('IPTM_BetaInEqB', PACKAGE = 'IPTM', nIP, lambdamat, edgebyC)
}

Timediff <- function(edge, node, when, lambda) {
    .Call('IPTM_Timediff', PACKAGE = 'IPTM', edge, node, when, lambda)
}

Dyadic <- function(history, node, sender) {
    .Call('IPTM_Dyadic', PACKAGE = 'IPTM', history, node, sender)
}

Triadic <- function(history, node, sender) {
    .Call('IPTM_Triadic', PACKAGE = 'IPTM', history, node, sender)
}

Degree <- function(history, node, sender) {
    .Call('IPTM_Degree', PACKAGE = 'IPTM', history, node, sender)
}

WordInEqZ <- function(K, textlistd, tableW, delta, nvec) {
    .Call('IPTM_WordInEqZ', PACKAGE = 'IPTM', K, textlistd, tableW, delta, nvec)
}

tabulateC <- function(x, max) {
    .Call('IPTM_tabulateC', PACKAGE = 'IPTM', x, max)
}

logWZ <- function(nIP, K, currentC, currentZ, textlist, tableW, alpha, mvec, delta, nvec) {
    .Call('IPTM_logWZ', PACKAGE = 'IPTM', nIP, K, currentC, currentZ, textlist, tableW, alpha, mvec, delta, nvec)
}

