# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Mahalanobis <- function(x, center, cov) {
    .Call('_IPTM_Mahalanobis', PACKAGE = 'IPTM', x, center, cov)
}

ei <- function(M) {
    .Call('_IPTM_ei', PACKAGE = 'IPTM', M)
}

dmvnorm_arma <- function(x, mean, sigma) {
    .Call('_IPTM_dmvnorm_arma', PACKAGE = 'IPTM', x, mean, sigma)
}

rmvnorm_arma <- function(n, mu, Sigma) {
    .Call('_IPTM_rmvnorm_arma', PACKAGE = 'IPTM', n, mu, Sigma)
}

transpose <- function(x) {
    .Call('_IPTM_transpose', PACKAGE = 'IPTM', x)
}

tabulateC <- function(x, max) {
    .Call('_IPTM_tabulateC', PACKAGE = 'IPTM', x, max)
}

Timepartsum <- function(mumat, sigma_tau, senders, timestamps) {
    .Call('_IPTM_Timepartsum', PACKAGE = 'IPTM', mumat, sigma_tau, senders, timestamps)
}

Timepartsum2 <- function(mumat, senders, timestamps) {
    .Call('_IPTM_Timepartsum2', PACKAGE = 'IPTM', mumat, senders, timestamps)
}

Timepartindiv <- function(mu, sigma_tau, timestamp) {
    .Call('_IPTM_Timepartindiv', PACKAGE = 'IPTM', mu, sigma_tau, timestamp)
}

Timepartindiv2 <- function(mu, timestamp) {
    .Call('_IPTM_Timepartindiv2', PACKAGE = 'IPTM', mu, timestamp)
}

multinom_vec <- function(x) {
    .Call('_IPTM_multinom_vec', PACKAGE = 'IPTM', x)
}

normalizer <- function(lambda_da) {
    .Call('_IPTM_normalizer', PACKAGE = 'IPTM', lambda_da)
}

Edgepartsum <- function(lambda, u) {
    .Call('_IPTM_Edgepartsum', PACKAGE = 'IPTM', lambda, u)
}

mu_cpp <- function(Y, eta) {
    .Call('_IPTM_mu_cpp', PACKAGE = 'IPTM', Y, eta)
}

mu_cpp_d <- function(Y, eta) {
    .Call('_IPTM_mu_cpp_d', PACKAGE = 'IPTM', Y, eta)
}

lambda_cpp <- function(X_d, beta) {
    .Call('_IPTM_lambda_cpp', PACKAGE = 'IPTM', X_d, beta)
}

sample_int <- function(n, min, max) {
    .Call('_IPTM_sample_int', PACKAGE = 'IPTM', n, min, max)
}

u_cpp <- function(lambda, u) {
    .Call('_IPTM_u_cpp', PACKAGE = 'IPTM', lambda, u)
}

u_cpp_d <- function(lambda_d, u) {
    .Call('_IPTM_u_cpp_d', PACKAGE = 'IPTM', lambda_d, u)
}

